Add remote renaming via a new command; fix current /janame being unusable for snitches with spaces
CivMC/JukeAlert pull request #34
Opened 2022-08-11 20:06 UTC by awoo-civ

Supersedes https://github.com/CivMC/JukeAlert/pull/32.

Adds a new command `/janameat` instead of overloading `/janame` to allow for a more user-friendly experience - no need to use quotes to name snitches with spaces.

Tested:
 - `/janame` works as before:
   - Snitch names with spaces work.
 - `/janameat`:
   - Works when the world is provided.
   - Works when the world is omitted.
   - Works with snitch names with spaces.
   - Fails with reasonably helpful error messages on:
     - Too few arguments.
     - Unknown world.
     - Coordinates that are not numbers.
     - Snitch name not provided.

Thanks to @Aleksey-Terzi for support and the code in https://github.com/CivMC/JukeAlert/pull/32.

2022-08-11 23:16 UTC, Aleksey-Terzi requested changes
Thanks for the contribution but I think this PR conflicts with PR #32 and also it breaks the current `/janame` implementation.
Can we move "name with spaces and without double quotes" function to a new command instead of regressing `/janame` and introducing `/janameat`?

2022-08-11 23:31 UTC, awoo-civ commented
> I think this PR conflicts with PR #32

That is very much intentional, the idea is to leave `/janame` like it always was and to add a new command only for remote naming.

> it breaks the current /janame implementation

It reverts the most recent change, yes. That's in-line with the above.

> Can we move "name with spaces and without double quotes" function to a new command [...]

I don't understand, the only way this change can work is with two commands - one for local and one for remote naming.

> [...] instead of regressing /janame and introducing /janameat?

I wouldn't call it a regression, as the change's been there for a day or two at this point and we don't lose any functionality. It is a breaking change, but we have little reason to care about that.

---

The idea here is to have two commands instead of one in order to not have to use quotes for snitch names with spaces.

The reasoning being that fiddling around with quotes is annoying, but having two commands instead of one is basically inconsequential.

2022-08-12 01:50 UTC, Aleksey-Terzi commented
I see here two major problems:

1. The more free syntax (i.e. no double quotes) you propose could lead to mistakes that are hard to determine.
For example, `/janameat 300 100 300 Snitch` can be actually a mistake and it should be in real `/janameat 300 100 300 300 100 300 Snitch`
IMO, parametrized commands should have strict syntax

2. If we move "remote renaming" functionality to the separate command (i.e. `janameat`) then it mostly never will be used by people

What I propose is to move "name with spaces and without double quotes" functionality to the separate command and leave the current `/janame` as is.

PS. Jana Meat doesn't allow me to focus on the answering, it's like a never-ending "ha ha".

2022-08-12 02:02 UTC, awoo-civ commented
> 1. The more free syntax (i.e. no double quotes) you propose could lead to mistakes that are hard to determine.

That's what having two commands addresses. I think I exhaustively handled & tested all the various ways to misuse the command, see https://github.com/CivMC/JukeAlert/pull/34/commits/d00ff857ea31bf37452eb277f922e9902e4a35f0#diff-970a676413d87a8e072351569bd6e5c5244a83488d11c601203c508bd299fb0cR33.

> For example, `/janameat 300 100 300 Snitch` can be actually a mistake and it should be in real `/janameat 300 100 300 300 100 300 Snitch`

I don't understand, why is `/janameat 300 100 300 Snitch` wrong and what is `/janameat 300 100 300 300 100 300 Snitch` supposed to do?

> If we move "remote renaming" functionality to the separate command (i.e. `janameat`) then it mostly never will be used by people

Why? If anything, I expect it's going to be easier to discover for players due to autocomplete - when you type `/jan` in chat you get this:

![2022-08-12 02-00 ](https://user-images.githubusercontent.com/17804892/184271316-5ee34482-f577-4cfa-9a4d-baf97241c38e.png)

Pretty self-explanatory I'd say.

> What I propose is to move "name with spaces and without double quotes" functionality to the separate command and leave the current `/janame` as is.

Again, it's not possible to have a single command that does this, hence the two-commands proposal.

> PS. Jana Meat doesn't allow me to focus on the answering, it's like a never-ending "ha ha".

Yeah the name is a little funny, though I'm not sure the alternatives are much better:
 - `/janameremote`
 - `/janamedistant`

2022-08-12 02:10 UTC, Aleksey-Terzi commented
We can continue arguing to infinity.
I've described why changes, as they are now, are not good.
Therefore I won't support changes as they are now.

Though of course, you can try to convince others to approve PR.

2022-08-12 02:26 UTC, grepsedawk commented
Personally, I feel the overload is much nicer.
`/janame 300 100 200 Bare Words Name` is a nice API, and taking the assumption that 3 ints in a row is "a x y z coordinate" is fair.

2022-08-12 02:36 UTC, awoo-civ commented
> Personally, I feel the overload is much nicer. `/janame 300 100 200 Bare Words Name` is a nice API, and taking the assumption that 3 ints in a row is "a x y z coordinate" is a fair compromise to getting all of this functionality into 1 overloaded command while still allowing bare words
> 
> `/janame [world] [x y z] name`

That would be nice but isn't how it works currently - you need to use quotes:
`/janame 300 100 200 "Bare Words Name"`, hence this proposal.

Allowing such a flexible /janame would be possible, though it'd be much trickier. There's no way to reliably tell if `/janame 300 100 200 Bare Words Name` is supposed to be 3 coordinates + a name or just a name. The existence of an optional `world` argument complicates it even further. I'm not sure that it'd be possible to come up with half-decent error messages for such a command.

2022-08-13 13:07 UTC, wingzero54 commented
I do not see why using one command is an issue. If we ignore the world argument, then janame can either have:
- three numbers and then anything else
janame 100 0 100 This is a remote snitch
or
- any other combination
janame 100 0 This is not a remote snitch
janame 100 0 100 100 0 100 This is a remote snitch

And if you enter them in incorrectly, you just re-do the command correctly. I don't have any fundamental issue with splitting into two commands, but I do think it would really restrict the number of people who know about and use the command to remotely rename, and that in itself is a reason not to split it up.

2022-08-13 13:27 UTC, awoo-civ commented
If we don't need to support the `world` argument then it gets a bit easier, yes.

> I do think it would really restrict the number of people who know about and use the command to remotely rename, and that in itself is a reason not to split it up.

Actually, as the plugin is right now, there's no autocomplete for `/janame`'s arguments, but there's one for commands, so I think it's the other way around. From my earlier comment:

> Why? If anything, I expect it's going to be easier to discover for players due to autocomplete - when you type `/jan` in chat you get this:
> 
> ![2022-08-12 02-00 ](https://user-images.githubusercontent.com/17804892/184271316-5ee34482-f577-4cfa-9a4d-baf97241c38e.png)
> 
> Pretty self-explanatory I'd say, the name notwithstanding.

2022-08-17 15:30 UTC, merged